### ISSUE TITLE
Allow to enable regex for file name

### ISSUE THREAD

**Issue by Frago9876543210** [i3h/download-release-asset#2]
https://github.com/i3h/download-release-asset/blob/8bbef9dca05d9aca53b6811e4c811ffe157bc844/src/download-release-asset.js#L43-L50

**Comment by Frago9876543210** [comment]
It will be useful for assets which contains version
![изображение](https://user-images.githubusercontent.com/13465245/85584637-fc4c1800-b647-11ea-91e2-003cede843de.png)

**Comment by i3h** [comment]
Thank you for feedback. I have added support for file name regex.

You now can provide a plain file name (abc-2.txt) or a regex as file name (/abc-[0-9]+.txt/) with slash symbol.

All of matched files will be downloaded.
