### ISSUE TITLE
Specifying output directory

### ISSUE THREAD

**Issue by Frago9876543210** [i3h/download-release-asset#5]
Would be useful to implement that instead of using root folder

**Comment by i3h** [comment]
Hello,

A new release has been published with the option "path".

Thanks for your advice!

**Comment by Frago9876543210** [comment]
Windows not supported yet? I guess there is something like mkdir -p in powershell

**Comment by i3h** [comment]
> Windows not supported yet? I guess there is something like mkdir -p in powershell

Great, I have implemented this feature on Windows with the help of powershell.
